### ISSUE TITLE
invalid character '/' in name

### ISSUE THREAD

**Issue by nc6** [nmattia/snack#29]
Trying to build the `funflow` package using this branch:

https://github.com/tweag/funflow/tree/nc/snack/funflow

```
> snack build --package-yaml ./package.yaml
```

Results in the following error:
>>>
error: invalid character '/' in name 'Control/Funflow/External/Executor.hs-single-out'
(use '--show-trace' to show detailed location information)
snack:
Ran commands:
nix-build - --no-out-link --argstr specJson '{
  "owner": "NixOS",
  "repo": "nixpkgs",
  "rev": "584270e39743020d8aa056b40eea00fcaa2b595f",
  "sha256": "1p8hrz7xz73gzcqw62f3zfkmf3pkwwn1b41xzs7ayxafkmzsh0hw"
}

**Comment by nmattia** [comment]
N.B.: https://github.com/tweag/funflow/tree/cebf994d1d969cefb0758b978aab31aff5f92337/funflow

**Comment by nmattia** [comment]
Ok I'm pretty sure the issue is here: https://github.com/nmattia/snack/blob/dde00575c5c844cf5d32ce397ad3205103c81dc0/snack-lib/files.nix#L27

The entire file name is passed as the derivation name, which Nix is unhappy about. There's apparently no function Nixpkgs to nixify a name but @zimbatm pointed out that this could be reused: 

https://github.com/moretea/yarn2nix/blob/8df1cee02f53bbb58ec0479fad5cca6ee3def170/default.nix#L15-L24
