### ISSUE TITLE
No `snack test` capability

### ISSUE THREAD

**Issue by Heimdell** [nmattia/snack#32]
The most used thing of `stack` I use is `stack test --nix --fast`.
Is there anything like that here?

**Comment by nmattia** [comment]
Very good question!

The `--nix` doesn't have a counterpart in snack because snack only uses nix. For `--test` I'm not sure how to go about this yet. Snack will need to support some notion of flags and will need to be able to differentiate executables (proper executable, test executable, benchmark). It's something that's been on my mind but I have no action plan yet, all suggestions are welcome. Something like `--fast` could be added easily (which would simply override the ghc options) but I personally find that GHCi is must better for fast builds and use full builds (no `--fast`) when they're really needed. Can you tell me a bit more about your workflow?

**Comment by nmattia** [comment]
@Heimdell I've thought about this a bit more, and I'm still not sure that having a `test` command is a good idea. The reasons for that is that there are too many levels of testing, which can't all be supported without settings up some kind of environment in which the test can be run:
* Type checking (handled by GHC).
* Unit tests (like `stack test`).
* Integration tests, system tests, etc (those often require a lot of machinery).

I think the best solution is to provide `snack run <foo>` where `<foo>` is some component. Then you can have a component called `test` and run `stack run test`. Would that work for you?

**Comment by nmattia** [comment]
I'm still in favor of `snack -s test.nix run`. Feel free to reopen if that's not satisfactory.
