### ISSUE TITLE
Snack fails when parsing a function name ending in `#`

### ISSUE THREAD

**Issue by nc6** [nmattia/snack#39]
Given the following block:

```
module Control.Funflow.ContentHashable
  ( ContentHash
  , toBytes
  , fromBytes
  , ContentHashable (..)
  , contentHashUpdate_binaryFile
  , contentHashUpdate_byteArray#
```
snack fails to compile with:
```
building '/nix/store/58y16n8xzfqaddmp5md2dc6vwy2jmcf7-dependencies-json.drv'...
3brwfgfxyk8xjfky4dvbb84vgpdzggdk-import-parser: user error (ParseFailed (SrcLoc "<unknown>.hs" 30 32) "Parse error: #")
builder for '/nix/store/58y16n8xzfqaddmp5md2dc6vwy2jmcf7-dependencies-json.drv' failed with exit code 1
error: build of '/nix/store/58y16n8xzfqaddmp5md2dc6vwy2jmcf7-dependencies-json.drv' failed
```

**Comment by nmattia** [comment]
N.B.: https://github.com/tweag/funflow/blob/37822cdfa3109181afedb4903359db47b58cee45/funflow/src/Control/Funflow/ContentHashable.hs

**Comment by pikajude** [comment]
this might be a bug in HSE. That source file specifies `{-# LANGUAGE MagicHash #-}`, but HSE can only actually parse it for me if I use `parseWithMode (defaultParseMode { extensions = [EnableExtension MagicHash] })` instead of `parse`. It might be worth enabling that extension by default if this is actually a bug.
